name: Build and test

on: [push, pull_request]

jobs:
  build-latest:
    name: Build and test latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Bootstrap
        run: |
          sudo apt-get install python3-setuptools
      - name: mkdir build
        run: mkdir build
      - name: cmake ..
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
      - name: make
        run: |
          cd build
          make
      - name: ctest .
        run: |
          cd build
          ctest -VV .

  build-latest-clang:
    name: Build and test latest clang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Bootstrap
        run: |
          sudo apt-get install clang
      - name: mkdir build
        run: mkdir build
      - name: cmake ..
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" ..
      - name: make
        run: |
          cd build
          make
      - name: ctest .
        run: |
          cd build
          ctest -VV .

  build-1604:
    name: Build and test 16.04
    runs-on:  ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Bootstrap
        run: |
          sudo apt-get install python3-setuptools
      - name: mkdir build
        run: mkdir build
      - name: cmake ..
        run: |
          cd build
          cmake  -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
      - name: make
        run: |
          cd build
          make
      - name: ctest .
        run: |
          cd build
          ctest -VV .
